=begin comment

DialMyCalls API

The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::DialMyCalls::AccountsApi');

my $api = WWW::DialMyCalls::AccountsApi->new();
isa_ok($api, 'WWW::DialMyCalls::AccountsApi');

#
# create_access_account test
#
{
    my $create_access_account_parameters = undef; # replace NULL with a proper value
    my $result = $api->create_access_account(create_access_account_parameters => $create_access_account_parameters);
}

#
# delete_access_account_by_id test
#
{
    my $access_account_id = undef; # replace NULL with a proper value
    my $result = $api->delete_access_account_by_id(access_account_id => $access_account_id);
}

#
# get_access_account_by_id test
#
{
    my $access_account_id = undef; # replace NULL with a proper value
    my $result = $api->get_access_account_by_id(access_account_id => $access_account_id);
}

#
# get_access_accounts test
#
{
    my $range = undef; # replace NULL with a proper value
    my $result = $api->get_access_accounts(range => $range);
}

#
# get_account test
#
{
    my $result = $api->get_account();
}

#
# update_access_account_by_id test
#
{
    my $update_access_account_by_id_parameters = undef; # replace NULL with a proper value
    my $access_account_id = undef; # replace NULL with a proper value
    my $result = $api->update_access_account_by_id(update_access_account_by_id_parameters => $update_access_account_by_id_parameters, access_account_id => $access_account_id);
}


1;
