=begin comment

DialMyCalls API

The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::DialMyCalls::RecordingsApi');

my $api = WWW::DialMyCalls::RecordingsApi->new();
isa_ok($api, 'WWW::DialMyCalls::RecordingsApi');

#
# create_recording test
#
{
    my $create_recording_parameters = undef; # replace NULL with a proper value
    my $result = $api->create_recording(create_recording_parameters => $create_recording_parameters);
}

#
# create_recording_by_phone test
#
{
    my $create_recording_by_phone_parameters = undef; # replace NULL with a proper value
    my $result = $api->create_recording_by_phone(create_recording_by_phone_parameters => $create_recording_by_phone_parameters);
}

#
# create_recording_by_url test
#
{
    my $create_recording_by_url_parameters = undef; # replace NULL with a proper value
    my $result = $api->create_recording_by_url(create_recording_by_url_parameters => $create_recording_by_url_parameters);
}

#
# delete_recording_by_id test
#
{
    my $recording_id = undef; # replace NULL with a proper value
    my $result = $api->delete_recording_by_id(recording_id => $recording_id);
}

#
# get_recording_by_id test
#
{
    my $recording_id = undef; # replace NULL with a proper value
    my $result = $api->get_recording_by_id(recording_id => $recording_id);
}

#
# get_recordings test
#
{
    my $range = undef; # replace NULL with a proper value
    my $result = $api->get_recordings(range => $range);
}

#
# update_recording_by_id test
#
{
    my $update_recording_by_id_parameters = undef; # replace NULL with a proper value
    my $recording_id = undef; # replace NULL with a proper value
    my $result = $api->update_recording_by_id(update_recording_by_id_parameters => $update_recording_by_id_parameters, recording_id => $recording_id);
}


1;
