=begin comment

DialMyCalls API

The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::DialMyCalls::TextsApi');

my $api = WWW::DialMyCalls::TextsApi->new();
isa_ok($api, 'WWW::DialMyCalls::TextsApi');

#
# cancel_text_by_id test
#
{
    my $text_id = undef; # replace NULL with a proper value
    my $result = $api->cancel_text_by_id(text_id => $text_id);
}

#
# create_text test
#
{
    my $create_text_parameters = undef; # replace NULL with a proper value
    my $result = $api->create_text(create_text_parameters => $create_text_parameters);
}

#
# delete_incoming_text_by_id test
#
{
    my $text_id = undef; # replace NULL with a proper value
    my $result = $api->delete_incoming_text_by_id(text_id => $text_id);
}

#
# get_incoming_text_by_id test
#
{
    my $text_id = undef; # replace NULL with a proper value
    my $result = $api->get_incoming_text_by_id(text_id => $text_id);
}

#
# get_incoming_texts test
#
{
    my $range = undef; # replace NULL with a proper value
    my $result = $api->get_incoming_texts(range => $range);
}

#
# get_short_codes test
#
{
    my $range = undef; # replace NULL with a proper value
    my $result = $api->get_short_codes(range => $range);
}

#
# get_text_by_id test
#
{
    my $text_id = undef; # replace NULL with a proper value
    my $result = $api->get_text_by_id(text_id => $text_id);
}

#
# get_text_recipients_by_text_id test
#
{
    my $text_id = undef; # replace NULL with a proper value
    my $range = undef; # replace NULL with a proper value
    my $result = $api->get_text_recipients_by_text_id(text_id => $text_id, range => $range);
}

#
# get_texts test
#
{
    my $range = undef; # replace NULL with a proper value
    my $result = $api->get_texts(range => $range);
}


1;
