=begin comment

DialMyCalls API

The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::DialMyCalls::VanityNumbersApi');

my $api = WWW::DialMyCalls::VanityNumbersApi->new();
isa_ok($api, 'WWW::DialMyCalls::VanityNumbersApi');

#
# delete_vanity_number_by_id test
#
{
    my $vanity_number_id = undef; # replace NULL with a proper value
    my $result = $api->delete_vanity_number_by_id(vanity_number_id => $vanity_number_id);
}

#
# get_vanity_number_by_id test
#
{
    my $vanity_number_id = undef; # replace NULL with a proper value
    my $result = $api->get_vanity_number_by_id(vanity_number_id => $vanity_number_id);
}

#
# get_vanity_numbers test
#
{
    my $range = undef; # replace NULL with a proper value
    my $result = $api->get_vanity_numbers(range => $range);
}

#
# update_vanity_number_by_id test
#
{
    my $update_vanity_number_by_id_parameters = undef; # replace NULL with a proper value
    my $vanity_number_id = undef; # replace NULL with a proper value
    my $result = $api->update_vanity_number_by_id(update_vanity_number_by_id_parameters => $update_vanity_number_by_id_parameters, vanity_number_id => $vanity_number_id);
}


1;
