=begin comment

DialMyCalls API

The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::DialMyCalls::Object::Callservice;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

DialMyCalls API

The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::DialMyCalls::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'Callservice',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'UUID',
    	base_name => 'id',
    	description => 'Unique identifier for this service.',
    	format => '',
    	read_only => '',
    		},
    'accessaccount_id' => {
    	datatype => 'UUID',
    	base_name => 'accessaccount_id',
    	description => 'Unique identifier for the access account which initiated this if available.',
    	format => '',
    	read_only => '',
    		},
    'name' => {
    	datatype => 'string',
    	base_name => 'name',
    	description => 'The name of the service.',
    	format => '',
    	read_only => '',
    		},
    'recording_id' => {
    	datatype => 'UUID',
    	base_name => 'recording_id',
    	description => 'Unique identifier for the recording.',
    	format => '',
    	read_only => '',
    		},
    'pending_cancel' => {
    	datatype => 'boolean',
    	base_name => 'pending_cancel',
    	description => 'Whether the service has been flagged to be cancelled.',
    	format => '',
    	read_only => '',
    		},
    'credit_cost' => {
    	datatype => 'double',
    	base_name => 'credit_cost',
    	description => 'The amount of credits required to schedule this service.',
    	format => '',
    	read_only => '',
    		},
    'total_recipients' => {
    	datatype => 'Number',
    	base_name => 'total_recipients',
    	description => 'The amount of recipients for this service.',
    	format => '',
    	read_only => '',
    		},
    'send_at' => {
    	datatype => 'string',
    	base_name => 'send_at',
    	description => 'When the service will be sent.',
    	format => '',
    	read_only => '',
    		},
    'created_at' => {
    	datatype => 'string',
    	base_name => 'created_at',
    	description => 'When the service was created.',
    	format => '',
    	read_only => '',
    		},
    'updated_at' => {
    	datatype => 'string',
    	base_name => 'updated_at',
    	description => 'When the service was last updated.',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'id' => 'UUID',
    'accessaccount_id' => 'UUID',
    'name' => 'string',
    'recording_id' => 'UUID',
    'pending_cancel' => 'boolean',
    'credit_cost' => 'double',
    'total_recipients' => 'Number',
    'send_at' => 'string',
    'created_at' => 'string',
    'updated_at' => 'string'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'accessaccount_id' => 'accessaccount_id',
    'name' => 'name',
    'recording_id' => 'recording_id',
    'pending_cancel' => 'pending_cancel',
    'credit_cost' => 'credit_cost',
    'total_recipients' => 'total_recipients',
    'send_at' => 'send_at',
    'created_at' => 'created_at',
    'updated_at' => 'updated_at'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
