=begin comment

DialMyCalls API

The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::DialMyCalls::Object::CreateTextParameters;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

DialMyCalls API

The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::DialMyCalls::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'CreateTextParameters',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'name' => {
    	datatype => 'string',
    	base_name => 'name',
    	description => '(Required)  Name the broadcast.',
    	format => '',
    	read_only => '',
    		},
    'keyword_id' => {
    	datatype => 'UUID',
    	base_name => 'keyword_id',
    	description => '(Required)  The keyword id that should be associated with this broadcast.',
    	format => '',
    	read_only => '',
    		},
    'messages' => {
    	datatype => 'ARRAY[string]',
    	base_name => 'messages',
    	description => '(Required)  List of messages to send (up to 10).',
    	format => '',
    	read_only => '',
    		},
    'send_at' => {
    	datatype => 'string',
    	base_name => 'send_at',
    	description => 'When the broadcast should be sent. (Ex: 2016-07-25T12:00:00+0000)',
    	format => '',
    	read_only => '',
    		},
    'send_immediately' => {
    	datatype => 'boolean',
    	base_name => 'send_immediately',
    	description => 'Should the broadcast go out immediately?',
    	format => '',
    	read_only => '',
    		},
    'send_email' => {
    	datatype => 'boolean',
    	base_name => 'send_email',
    	description => 'Also send an email to the contacts?',
    	format => '',
    	read_only => '',
    		},
    'accessaccount_id' => {
    	datatype => 'UUID',
    	base_name => 'accessaccount_id',
    	description => 'Schedule this broadcast as an access account.',
    	format => '',
    	read_only => '',
    		},
    'shortcode_id' => {
    	datatype => 'UUID',
    	base_name => 'shortcode_id',
    	description => 'The shortcode id that the broadcast will be sent from.',
    	format => '',
    	read_only => '',
    		},
    'concatenate_sms' => {
    	datatype => 'boolean',
    	base_name => 'concatenate_sms',
    	description => 'Combine all SMS messages into 1 message on the end users device.',
    	format => '',
    	read_only => '',
    		},
    'contacts' => {
    	datatype => 'ARRAY[ContactAttributes]',
    	base_name => 'contacts',
    	description => '(Required)  List of contact information that should be sent the broadcast.',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'name' => 'string',
    'keyword_id' => 'UUID',
    'messages' => 'ARRAY[string]',
    'send_at' => 'string',
    'send_immediately' => 'boolean',
    'send_email' => 'boolean',
    'accessaccount_id' => 'UUID',
    'shortcode_id' => 'UUID',
    'concatenate_sms' => 'boolean',
    'contacts' => 'ARRAY[ContactAttributes]'
} );

__PACKAGE__->attribute_map( {
    'name' => 'name',
    'keyword_id' => 'keyword_id',
    'messages' => 'messages',
    'send_at' => 'send_at',
    'send_immediately' => 'send_immediately',
    'send_email' => 'send_email',
    'accessaccount_id' => 'accessaccount_id',
    'shortcode_id' => 'shortcode_id',
    'concatenate_sms' => 'concatenate_sms',
    'contacts' => 'contacts'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
